### PR TITLE
Remove permalink blank page

### PR DESCRIPTION
**Pull request by schrauger**
**Description**
Removes the permalink and blank page created by the custom post type.

**Motivation and Context**

Spotlight custom post types created blank pages and permalinks that were searchable. Since spotlights are only used as a shortcode to be used on another page, this blank page is not needed and causes issues with searching and crawling the site.

**How Has This Been Tested?**

Tested on my local site and the development site for UCF College of Medicine.

**Types of changes**

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

**Checklist:**

- [x] My code follows the code style of this project.
- [x] My change requires an update to the documentation.
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by cjg89** [comment]
Thanks for contributing to this plugin!  Unfortunately we can't accept this change for a couple of reasons:

1. This change effectively removes the ability to retrieve a spotlight's slug from anywhere in the WordPress admin.  The `[ucf-spotlight]` shortcode expects a post slug to be passed to it to retrieve a specific Spotlight to display, so we need logged in users to be able to easily determine what the slug of any Spotlight is to be able to use the shortcode without having to guess what the generated slug would be.
2. This change requires a permalink flush to fully take effect, which would either require adding a programmatic permalink flush on plugin update (which has its own separate set of challenges), or making this update a breaking change (a bump to v3.0.0).

The lack of a default template for single Spotlights, and the fact that they are publicly crawled and added to sitemaps, is still problematic though.  We tend to work around this by using the UCF WordPress Theme (which provides a `single-ucf_spotlight.php` to allow previewing of single Spotlights--so you don't see a blank page), and by using Yoast SEO to explicitly disable crawling on all Spotlight posts.  But yes, ideally the Spotlight plugin should provide a base template and a means of preventing undesired access to single Spotlight posts.

An ideal solution for this issue would involve:
a) Adding a default `single-ucf_spotlight.php` template to the plugin that gets loaded when the current theme hasn't already defined one,
b) Remove the Spotlight post type from WP's generated sitemaps (as of WP 5.5), and
c) Ensure single Spotlights have a `noindex` meta tag in the document head, _or_ add some sort of `template_redirect` override for single Spotlights to ensure that only logged-in users can view them

Let us know what you think about the alternatives listed above.  Thanks!

**Comment by schrauger** [comment]
I didn't realize my simple change caused those other issues. Glad you caught it. I'll look into the alternatives and see if I can add the default template and other things needed. We are already using the ucf colleges WordPress theme, so that should help.

**Comment by cjg89** [comment]
Hey @schrauger , I've opened a new pull request that incorporates the changes needed to fix this issue: https://github.com/UCF/UCF-Spotlights-Plugin/pull/34

If you're able to pull down the new branch and let us know if it works out for you in your Dev/QA environment, we'd appreciate it!  I'm going to close out this PR; feel free to comment on the new PR or #33 if you have anything else to add.  Thanks!

**Comment by cjg89** [comment]
@schrauger v2.1.0 includes updates that resolve the blank template and crawling issues for Spotlights.  Please give it a try and feel free to open a new issue if you encounter any other problems.  Thanks!

**Pull request closed without merging**
